### PR TITLE
New  Plugin: LIFX

### PR DESCRIPTION
**Pull request by Boernsman**
nymea-plugins pull request checklist:

- [x]  Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [x]  Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [x]  Did you update the plugin's README.md accordingly?

- [x]  Did you update translations (`cd builddir && make lupdate`)?

- [x]  If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

### CODE REVIEW

**Comment by mzanetti** [comment]
integrationpluginlifx.cpp: In member function ‘virtual void IntegrationPluginLifx::executeAction(ThingActionInfo*)’:
integrationpluginlifx.cpp:373:49: error: ‘effect’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  373 |                 requestId = lifxCloud->setEffect(lightId, effect, "#FFFFFF");
      |                             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
integrationpluginlifx.cpp:294:48: error: ‘lifxCloud’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  294 |                 requestId = lifxCloud->setPower(lightId, power);
      |                             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
integrationpluginlifx.cpp:332:43: error: ‘lifx’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  332 |                 requestId = lifx->setColor(color);
      |                             ~~~~~~~~~~~~~~^~~~~~~

**Review by mzanetti — DISMISSED** [review]
fails the build

**Comment by Boernsman** [comment]
> fails the build

**Comment by Boernsman** [comment]
> fails the build

fixed

**Comment by mzanetti** [comment]
I'm confused... 
the authentication method is userandpassword. Yet, the user needs to enter a token. Wouldn't "displayPin" be more appropriate?

**Comment by Boernsman** [comment]
> I'm confused...
> the authentication method is userandpassword. Yet, the user needs to enter a token. Wouldn't "displayPin" be more appropriate?

The account interface requires an username, the username is not required to authenticate but for the user it is good to know which user is logged in, though any username can be entered during the setup process

**Comment by mzanetti** [comment]
> > I'm confused...
> > the authentication method is userandpassword. Yet, the user needs to enter a token. Wouldn't "displayPin" be more appropriate?
> 
> The account interface requires an username, the username is not required to authenticate but for the user it is good to know which user is logged in, though any username can be entered during the setup process

Normally cloud apis have means to obtain the proper name (as in full name, not a username) for a token... It's meant for that.

**Comment by mzanetti** [comment]
ok. I just checked the lifx api. indeed there are no means to retrieve the users name.

I guess this "workaround" is fine then...

I do feel like there's a mess in this code when it comes to dtermining whether a light is connected through cloud or local network. But given the local network implementation isn't completed, I suppose that's to be cleaned up in that step.

**Review by mzanetti — APPROVED** [review]
okay...

**Pull request merged**
