### PR TITLE
TcpCommander: Add TCP server broadcast functionality to send data to all connected clients

### PR DESCRIPTION
**Pull request by t-mon**
nymea-plugins pull request checklist:

- [x] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [x] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [x] Did you update the plugin's README.md accordingly?

- [x] Did you update translations (`cd builddir && make lupdate`)?

- [x] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

### CODE REVIEW

**Review by mzanetti — CHANGES_REQUESTED** [review]
Mostly ok, but the change to the connected logic is not good.

The current code intentionally only indicates being connected if at least one client is connected, given TCP allows us to know that.

If you really want to change that behavior (I probably wouldn't but don't have a strong opinion on it either), you'd also have to change the code in `onTcpServerConnectionCountChanged` to not set it to disconnected when the last client disconnects.

**Comment by t-mon** [comment]
> Mostly ok, but the change to the connected logic is not good.

Besides the fact that a server has no connected state, the state should reflect if the server is listening, not if there is a client connected. The client counter shows you how many are connected, but without this change, everything looks broken if no client is connected.

**Comment by mzanetti** [comment]
> > Mostly ok, but the change to the connected logic is not good.
> 
> Besides the fact that a server has no connected state, the state should reflect if the server is listening, not if there is a client connected. The client counter shows you how many are connected, but without this change, everything looks broken if no client is connected.

Fair enough. but then also the clientDisconnected slot needs to be fixed.

**Review by mzanetti — APPROVED** [review]
lgtm now

**Pull request merged**
