### PR TITLE
Nuimo: Remove Battery Critical state

### PR DESCRIPTION
**Pull request by simonseres**
Removed the BatteryCriticalState since battery level is not conveyed right anyway.

nymea-plugins pull request checklist:

- [x] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [x] Did you update the plugin's README.md accordingly?

- [x] Did you update translations (`cd builddir && make lupdate`)?

- [x] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

### CODE REVIEW

**Comment by mzanetti** [comment]
just removing this state won't work as it's a mandatory state of the "battery" interface... Possible options are:
* Fix the state reporting (preferred option)
* Leave it there but never actually set it to true
* Completely remove the battery interface and all its related states.

Can you explain a bit more what's wrong with this? Is it triggering too early (i.e. does the nuimo still run for a long time even if critical is reported) or is it flickering on/off repeatedly?

**Comment by simonseres** [comment]
> just removing this state won't work as it's a mandatory state of the "battery" interface... Possible options are:
got it
> 
> * Fix the state reporting (preferred option)
> * Leave it there but never actually set it to true
> * Completely remove the battery interface and all its related states.
thats the way to go
> 
> Can you explain a bit more what's wrong with this? Is it triggering too early (i.e. does the nuimo still run for a long time even if critical is reported) or is it flickering on/off repeatedly?

Battery is always shown at 0%. 
The battery status in the Nuimo plugin is overengineering anyways. Nuimo has this LED matrix that shows low battery. In practical life, there is no benefit of having this information in nymea.
And since Nuimo is not a popular device, roughly a handful of people use it with nymea. 
So it doesn't make sense spending more time on that issue (2 people spend some hours to make this work in the past).
I will remove the whole battery state then.

**Comment by mzanetti** [comment]
I've read up on this and have understood the issue... This doesn't only affect the nuimo tho, it affects most bluetooth devices. Also this should be working fine on maveo boxes, just not on other setups... tbh I'd prefer fixing it also for our rpi images/other installations. Mainly because it does not only affect the nuimo...

For a test, could you please create this file on your machine:
`/etc/systemd/system/bluetooth.service.d/01-disable-unwanted-plugins.conf`
with the content
```
[Service]
ExecStart=
ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=battery,sap
```

and then reboot? It should make it work.

**Comment by simonseres** [comment]
Created the file/content and rebooted.
Problem persists.
image

**Review by t-mon — CHANGES_REQUESTED** [review]
Why do we want to remove the battery state? 
I understand that depending on the bluez version the battery has to be handled different, but is it not working any more?

**Comment by mzanetti** [comment]
Closing this.

**Pull request closed without merging**
